### ISSUE TITLE
Track Certification Status

### ISSUE THREAD

**Issue by NegativeK** [hef/ps1auth#29] opened 2014-04-02 14:21 UTC
Track tool certification/authorization status with the member's site.

Cert status can be changed by recommended certifiers, et cetera.

Wiki becomes secondary source or irrelevant.

**Comment by ludagoo** [comment] 2015-05-02 04:38
Duplicate of #43?

**Comment by hef** [comment] 2015-05-08 03:25
next release will have group management features

**Closed by hef** 2015-05-08 03:25 UTC
